mindmap
  root((Ansible automation))
    Novice
    ::icon(fa fa-thumbs-up)
      Learn the basics
    User
    ::icon(fa fa-user)
      Write playbook
        How do I make my automation consistent?
        How do I make things reusable?
        How do I organize my project as my automation grows?
          How do I use roles to structure my project?
        How do I share my automation?
          How do I create a collection?
          How do I allow others to run my playbook?
            Running remotely
              AWX
                REST API
                Web UI
                cron
              How do I plan my deployment?
              How do I manage inventories?
            Running locally
              How do I use an execution environment?
          How do I add to a collection?
      Have something to automate
        SRE process
        Raspberry pi cluster
        Network devices
    Developer
    ::icon(fa fa-code)
      Creating a Python virtual environment
      Building execution environments
    Community maintainer
    ::icon(fa fa-users)
      Starting point one
      Starting point two
      Starting point three
    Community member
    ::icon(fa fa-cat)
      Starting point one
      Starting point two
      Starting point three
